### ISSUE TITLE
Issue with serializing date

### ISSUE THREAD

**Issue by mkdskd** [hl7-fhir/fhir-svn#4]
In DSTU2 while serialising **condition** resource it's giving value of **dateAsserted** having time component in it. Which is not supported by library anymore.

We try to set *dateAsserted* for *condition* using following method defined in **Condition.java**.

![set_condition](https://cloud.githubusercontent.com/assets/5915340/6284810/a900a178-b91a-11e4-8f23-cb373f0bb25a.png)

It's creating a *new DateType()* which internally does this

![basic_date_time_type](https://cloud.githubusercontent.com/assets/5915340/6284856/13e9085e-b91b-11e4-82f4-7d43b9e13f8b.png)

If we see in Line number 91

    private TemporalPrecisionEnum myPrecision = TemporalPrecisionEnum.SECOND;

the **precision** is being set to *SECOND*, which is causing the **date** value having time component.

**Comment by jmandel** [comment]
Thanks for the report @mkdskd ! I've shared it with the FHIR Core team. I'm actually going to close this issue because the Github repo is just a mirror of FHIR's official svn repo. In the future, you can report issues via the official tracker (sorry -- it's not nearly as pleasant to use at Github. We're working on moving away from it, but for the time being, it's what we have.):
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemAdd&tracker_id=677
